---
name: Release

on:
  push:
    branches: [main]

concurrency:
  group: release

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yaml

  release:
    name: Release
    needs: ci
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.new-release-version }}
      published: ${{ steps.version.outputs.new-release-published }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
      - id: version
        uses: open-turo/actions-release/semantic-release@4d8a6b6aa2d051e7dba0429d8d08beef827b5ccd # v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
          ci: false

  publish:
    name: Publish
    needs: release
    runs-on: ubuntu-latest
    if: needs.release.outputs.published == 'true'
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - id: authenticate
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2
        with:
          app-id: ${{ secrets.BOT_CLIENT_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          token: ${{ steps.authenticate.outputs.token }}
          fetch-depth: 0
      - id: version
        uses: open-turo/actions-release/semantic-release@4d8a6b6aa2d051e7dba0429d8d08beef827b5ccd # v4
        with:
          github-token: ${{ steps.authenticate.outputs.token }}
          dry-run: true
          ci: false
      - uses: actions-js/push@master
        with:
          message: "chore: ${{ steps.version.outputs.new-release-version }} [skip actions]"
          github_token: ${{ steps.authenticate.outputs.token }}
      - uses: open-turo/actions-release/semantic-release@4d8a6b6aa2d051e7dba0429d8d08beef827b5ccd # v4
        with:
          github-token: ${{ steps.authenticate.outputs.token }}
